#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox=/system/etc/L_SPEED/00L_STUFF/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/LS_kernel_sleepers.log

$busybox rm -f $LS
$busybox touch $LS

$busybox echo "# L Speed log" | $busybox tee -a $LS
$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Applying kernel sleepers.." | $busybox tee -a $LS

# Kernel sleepers
mount -t debugfs none /sys/kernel/debug
$busybox mount -t debugfs none /sys/kernel/debug
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_AFFINE_WAKEUPS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_ARCH_POWER" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_CACHE_HOT_BUDDY" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_DOUBLE_TICK" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_FORCE_SD_OVERLAP" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_GENTLE_FAIR_SLEEPERS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_HRTICK" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_LAST_BUDDY" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_LB_BIAS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_LB_MIN" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NEW_FAIR_SLEEPERS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NEXT_BUDDY" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NONTASK_POWER" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_NORMALIZED_SLEEPERS" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_OWNER_SPIN" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_RT_RUNTIME_SHARE" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_START_DEBIT" >> /sys/kernel/debug/sched_features
fi
if [ -e "/sys/kernel/debug/sched_features" ]; then
	$busybox echo "NO_TTWU_QUEUE" >> /sys/kernel/debug/sched_features
fi
$busybox umount /sys/kernel/debug

$busybox echo "" | $busybox tee -a $LS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Kernel sleepers applied" | $busybox tee -a $LS
